name = "Ensembles"
uuid = "6e62b0a0-f6e2-496f-914a-544f223f57d3"
authors = ["Grant Bruer gbruer15@gmail.com and contributors"]
version = "1.0.0-DEV"

[deps]
PackageExtensionCompat = "65ce6f38-6b18-4e1d-a461-8949797d7930"

[weakdeps]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[extensions]
RandomExt = "Random"

[compat]
PackageExtensionCompat = "1"
julia = "1.8"
Random = "1.7"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
